<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobs = [
            [
                'category_id' => 6,
                'title' => 'Provident quo nostr',
                'description' => '<h5>Essential Knowledge, Skills, and Experience</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-3.png',
                'company' => 'Kinney and Hines Associates',
                'company_logo' => 'assets/company_images/logo-3.svg',
                'company_web_link' => 'https://solomonandryantrading.com',
                'location' => 'Culpa sapiente vel e',
                'salary' => '$120k - $130k',
                'start_date' => '2024-08-23',
                'end_date' => '2024-10-17',
                'address' => 'Labore exercitation',
                'number' => '762465467',
                'email' => 'wupow@mailinator.com',
                'time_slot' => 'Sunt cumque in dolo',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'title' => 'Software Engineer',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-4.png',
                'company' => 'Tech Solutions Ltd.',
                'company_logo' => 'assets/company_images/logo-4.svg',
                'company_web_link' => 'https://techsolutions.com',
                'location' => 'San Francisco, CA',
                'salary' => '$90k - $100k',
                'start_date' => '2024-07-01',
                'end_date' => '2024-08-31',
                'address' => '123 Main St, San Francisco, CA 94105',
                'number' => '(415) 555-1234',
                'email' => 'info@techsolutions.com',
                'time_slot' => '9:00 - 17:00, Mon - Fri',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'title' => 'Registered Nurse',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-5.png',
                'company' => 'HealthCare Plus',
                'company_logo' => 'assets/company_images/logo-5.svg',
                'company_web_link' => 'https://healthcareplus.com',
                'location' => 'New York, NY',
                'salary' => '$70k - $80k',
                'start_date' => '2024-07-15',
                'end_date' => '2024-09-15',
                'address' => '456 Oak St, New York, NY 10001',
                'number' => '(212) 555-6789',
                'email' => 'careers@healthcareplus.com',
                'time_slot' => 'Day shift, flexible hours',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'title' => 'Digital Marketing Specialist',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-6.png',
                'company' => 'Growth Media Agency',
                'company_logo' => 'assets/company_images/logo-6.svg',
                'company_web_link' => 'https://growthmedia.com',
                'location' => 'Chicago, IL',
                'salary' => '$55k - $65k',
                'start_date' => '2024-07-10',
                'end_date' => '2024-08-30',
                'address' => '789 Maple Ave, Chicago, IL 60611',
                'number' => '(312) 555-4567',
                'email' => 'info@growthmedia.com',
                'time_slot' => 'Flexible, remote possible',
                'is_remote' => 1,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 9,
                'title' => 'Graphic Designer',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-7.png',
                'company' => 'Creative Designs Co.',
                'company_logo' => 'assets/company_images/logo-4.svg',
                'company_web_link' => 'https://creativedesignsco.com',
                'location' => 'Los Angeles, CA',
                'salary' => '$40k - $50k',
                'start_date' => '2024-07-05',
                'end_date' => '2024-09-05',
                'address' => '890 Cedar St, Los Angeles, CA 90001',
                'number' => '(213) 555-7890',
                'email' => 'careers@creativedesignsco.com',
                'time_slot' => 'Flexible hours, remote friendly',
                'is_remote' => 1,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'title' => 'Elementary School Teacher',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-8.png',
                'company' => 'Bright Horizons Academy',
                'company_logo' => 'assets/company_images/logo-2.svg',
                'company_web_link' => 'https://bhacademy.com',
                'location' => 'Boston, MA',
                'salary' => '$50k - $60k',
                'start_date' => '2024-08-01',
                'end_date' => '2024-06-30',
                'address' => '123 Elm St, Boston, MA 02108',
                'number' => '(617) 555-2345',
                'email' => 'jobs@bhacademy.com',
                'time_slot' => 'School hours, full-time',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 10,
                'title' => 'HR Manager',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-9.png',
                'company' => 'PeopleFirst HR Solutions',
                'company_logo' => 'assets/company_images/logo-4.svg',
                'company_web_link' => 'https://peoplefirsthr.com',
                'location' => 'Seattle, WA',
                'salary' => '$70k - $80k',
                'start_date' => '2024-07-15',
                'end_date' => '2024-09-15',
                'address' => '456 Pine St, Seattle, WA 98101',
                'number' => '(206) 555-3456',
                'email' => 'careers@peoplefirsthr.com',
                'time_slot' => '9:00 - 17:00, Mon - Fri',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 12,
                'title' => 'Web Developer',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-10.png',
                'company' => 'WebTech Solutions',
                'company_logo' => 'assets/company_images/logo-6.svg',
                'company_web_link' => 'https://webtechsolutions.com',
                'location' => 'San Diego, CA',
                'salary' => '$80k - $90k',
                'start_date' => '2024-07-10',
                'end_date' => '2024-08-30',
                'address' => '789 Beach Blvd, San Diego, CA 92109',
                'number' => '(858) 555-4567',
                'email' => 'info@webtechsolutions.com',
                'time_slot' => 'Flexible, remote possible',
                'is_remote' => 1,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 8,
                'title' => 'Content Writer',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-1.png',
                'company' => 'Wordsmiths Inc.',
                'company_logo' => 'assets/company_images/logo-1.svg',
                'company_web_link' => 'https://wordsmiths.com',
                'location' => 'Portland, OR',
                'salary' => '$45k - $55k',
                'start_date' => '2024-07-05',
                'end_date' => '2024-09-05',
                'address' => '890 Oak St, Portland, OR 97201',
                'number' => '(503) 555-5678',
                'email' => 'careers@wordsmiths.com',
                'time_slot' => 'Flexible hours, remote friendly',
                'is_remote' => 1,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 7,
                'title' => 'System Analyst',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-3.png',
                'company' => 'DataSystems Ltd.',
                'company_logo' => 'assets/company_images/logo-1.svg',
                'company_web_link' => 'https://datasystems.com',
                'location' => 'Austin, TX',
                'salary' => '$75k - $85k',
                'start_date' => '2024-08-01',
                'end_date' => '2024-06-30',
                'address' => '123 Data Dr, Austin, TX 78701',
                'number' => '(512) 555-6789',
                'email' => 'jobs@datasystems.com',
                'time_slot' => 'Flexible hours, full-time',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'title' => 'Financial Analyst',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-10.png',
                'company' => 'FinanceExperts LLC',
                'company_logo' => 'assets/company_images/logo-2.svg',
                'company_web_link' => 'https://financeexperts.com',
                'location' => 'Houston, TX',
                'salary' => '$60k - $70k',
                'start_date' => '2024-07-15',
                'end_date' => '2024-09-15',
                'address' => '456 Finance Ave, Houston, TX 77002',
                'number' => '(713) 555-7890',
                'email' => 'careers@financeexperts.com',
                'time_slot' => '9:00 - 17:00, Mon - Fri',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 10,
                'title' => 'Marketing Manager',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-4.png',
                'company' => 'Marketers United',
                'company_logo' => 'assets/company_images/logo-3.svg',
                'company_web_link' => 'https://marketersunited.com',
                'location' => 'Miami, FL',
                'salary' => '$85k - $95k',
                'start_date' => '2024-07-10',
                'end_date' => '2024-08-30',
                'address' => '789 Marketing Blvd, Miami, FL 33101',
                'number' => '(305) 555-4567',
                'email' => 'info@marketersunited.com',
                'time_slot' => 'Flexible, remote possible',
                'is_remote' => 1,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 12,
                'title' => 'Mobile App Developer',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-6.png',
                'company' => 'AppMasters Inc.',
                'company_logo' => 'assets/company_images/logo-1.svg',
                'company_web_link' => 'https://appmasters.com',
                'location' => 'Denver, CO',
                'salary' => '$70k - $80k',
                'start_date' => '2024-07-05',
                'end_date' => '2024-09-05',
                'address' => '890 App Ave, Denver, CO 80201',
                'number' => '(303) 555-5678',
                'email' => 'careers@appmasters.com',
                'time_slot' => 'Flexible hours, remote friendly',
                'is_remote' => 1,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'title' => 'Customer Support Specialist',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-2.png',
                'company' => 'SupportHeroes Co.',
                'company_logo' => 'assets/company_images/logo-6.svg',
                'company_web_link' => 'https://supportheroes.com',
                'location' => 'Seattle, WA',
                'salary' => '$40k - $50k',
                'start_date' => '2024-08-01',
                'end_date' => '2024-06-30',
                'address' => '123 Support St, Seattle, WA 98101',
                'number' => '(206) 555-6789',
                'email' => 'jobs@supportheroes.com',
                'time_slot' => 'Flexible hours, full-time',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'title' => 'Operations Manager',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-8.png',
                'company' => 'OpsGenius Inc.',
                'company_logo' => 'assets/company_images/logo-5.svg',
                'company_web_link' => 'https://opsgenius.com',
                'location' => 'Boston, MA',
                'salary' => '$75k - $85k',
                'start_date' => '2024-07-15',
                'end_date' => '2024-09-15',
                'address' => '456 Ops St, Boston, MA 02108',
                'number' => '(617) 555-2345',
                'email' => 'careers@opsgenius.com',
                'time_slot' => '9:00 - 17:00, Mon - Fri',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'title' => 'Business Analyst',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-5.png',
                'company' => 'BizAnalytica',
                'company_logo' => 'assets/company_images/logo-1.svg',
                'company_web_link' => 'https://bizanalytica.com',
                'location' => 'San Diego, CA',
                'salary' => '$80k - $90k',
                'start_date' => '2024-07-10',
                'end_date' => '2024-08-30',
                'address' => '789 Biz Blvd, San Diego, CA 92109',
                'number' => '(858) 555-4567',
                'email' => 'info@bizanalytica.com',
                'time_slot' => 'Flexible, remote possible',
                'is_remote' => 1,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'title' => 'Sales Manager',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-9.png',
                'company' => 'SalesPro Solutions',
                'company_logo' => 'assets/company_images/logo-1.svg',
                'company_web_link' => 'https://salesprosolutions.com',
                'location' => 'Portland, OR',
                'salary' => '$45k - $55k',
                'start_date' => '2024-07-05',
                'end_date' => '2024-09-05',
                'address' => '890 Sales St, Portland, OR 97201',
                'number' => '(503) 555-5678',
                'email' => 'careers@salesprosolutions.com',
                'time_slot' => 'Flexible hours, remote friendly',
                'is_remote' => 1,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'title' => 'Project Manager',
                'description' => '<h5>Job Description</h5><p>The AliStudio Design team has a vision to establish a trusted platform that enablesproductive and healthy enterprises in a world of digital and remote everything, constantly changing work patterns and norms, and the need for organizational resiliency.</p>',
                'image' => 'assets/job_images/job-10.png',
                'company' => 'Project Masters Ltd.',
                'company_logo' => 'assets/company_images/logo-1.svg',
                'company_web_link' => 'https://projectmasters.com',
                'location' => 'Austin, TX',
                'salary' => '$75k - $85k',
                'start_date' => '2024-08-01',
                'end_date' => '2024-06-30',
                'address' => '123 Project Dr, Austin, TX 78701',
                'number' => '(512) 555-6789',
                'email' => 'jobs@projectmasters.com',
                'time_slot' => 'Flexible hours, full-time',
                'is_remote' => 0,
                'is_fulltime' => 1,
                'is_urgent' => 0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert data into jobs table
        DB::table('job')->insert($jobs);
    }
}
